name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!" 
      - name: ArgoCD CLI
        uses: imajeetyadav/argocd-cli@v1
        # with:
        #   # Version of the ArgoCD CLI to use
        #   version: # optional, default is latest
      - name: argocd login
        run: argocd login nemkovich.by --grpc-web-root-path /argocd --username admin --password ${{ secrets.AC_PASS }}
      - name: argocd app list
        run: argocd app list
      - name: argocd app sync
        run: argocd app sync portfolio
          
